# =============================================================================
#  config.example.py  --  TEMPLATE.  Do not edit this file for a store.
# =============================================================================
#  install.sh copies this to  config.py  on first install.
#  Edit the REAL file (config.py) on each Pi:   nano config.py
#  config.py is git-ignored, so credentials never get committed to GitHub.

# ----- Store identity --------------------------------------------------------
# Used to build the remote upload path (see REMOTE_FILE below).
STORE_NAME = "STORENAME"

# ----- Serial / ATG (Veeder-Root TLS-350) settings ---------------------------
SERIAL_PORT = "/dev/ttyUSB0"   # USB-serial adapter; check with: ls /dev/ttyUSB*
BAUDRATE    = 9600
COMMAND     = "i20100"         # in-tank inventory command
TANK        = "00"             # 00 = all tanks
TIMEOUT     = 10               # seconds

# ----- Local CSV path --------------------------------------------------------
# capture.py writes here; upload.py reads from here. Keep them the same.
CSV_PATH = "/home/admin/Documents/TESTTABLE.csv"

# ----- Product code -> name map ---------------------------------------------
# Product comes straight from the ATG; this just turns its numeric code into a
# readable name. Usually no need to change it per store.
PRODUCT_MAP = {
    "1": "REGULAR",
    "2": "PREMIUM",
    "3": "DIESEL",
}

# ----- SFTP upload settings --------------------------------------------------
SFTP_HOST     = "162.142.70.64"
SFTP_PORT     = 24566
SFTP_USER     = "gasreadings"
SFTP_PASSWORD = "PUT_PASSWORD_HERE"   # <-- set this on each Pi

# Remote destination. By default it is built from STORE_NAME:
#   /fuel/<STORE_NAME>/<STORE_NAME>TABLE.csv
# Override REMOTE_FILE directly if your layout differs.
REMOTE_FILE = f"/fuel/{STORE_NAME}/{STORE_NAME}TABLE.csv"
